### ISSUE TITLE
set libc type or glibc version

### ISSUE THREAD

**Issue by msalib** [DeterminateSystems/riff#117]
Is there any way to either ask for musl libraries or build with a particular glibc version (like `cargo zigbuild`) for folks who need to ship binaries to older systems running older libcs?

**Comment by grahamc** [comment]
We don't support this right now. We've been thinking / wondering about how to handle cross and other targets, but we're not ready to adopt that complexity yet. Maybe adding your musl packages to the build-inputs would be sufficient? I'm not sure -- if you do some experiments, we'd love to hear back.

**Comment by alekseysidorov** [comment]
I'd try to make it possible to specify the custom settings for the nix packages, or even use the custom nix file. 

Also, we can specify this nix custom packages to certain cargo targets.

Something like this:

```toml
[package.metadata.riff.targets.aarch64-apple-darwin]
# Just specify cross system
nixpkgs.crossSystem.config = "x86_64-unknown-linux-musl"
# Or use specific nix file
nixpkgs.fromFile = "config.nix"
```
